[build]
    publish = "public"

[build.environment]
    HUGO_VERSION = "0.124.0"
    HUGO_THEME = "hugo-theme-stack"

[context.production]
    command = "hugo --gc"
    [context.production.environment]
        HUGO_ENV = "production"

[context.branch-deploy]
    command = "hugo --gc"

[context.deploy-preview]
    command = "hugo --gc"

